language: r
cache: packages
sudo: false
warnings_are_errors: false
r_packages:
  - covr
  - RPostgreSQL
  - DBI
  - testthat
  - reticulate
os:
  - linux
brew_packages: python3
services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - python-dev
      - python
      - python3-dev
      - python3
    #  - sqlite3
      - r-cran-testthat
      - r-cran-dbi
      - r-cran-rpostgresql
      - r-cran-rmysql
      - r-cran-rsqlite
env:
  - R_PYTHON_VERSION=3
before_install:
  - export PATH=$(which python$R_PYTHON_VERSION):$PATH
  - export PYTHON=$(which python$R_PYTHON_VERSION)
  - export PYTHONPATH=$(which python$R_PYTHON_VERSION):$PYTHONPATH
install:
  - R -e 'install.packages(c("devtools"));if (!all(c("devtools") %in% installed.packages())) { q(status = 1, save = "no")}'
  - R -e 'library(devtools);devtools::install_github("klutometis/roxygen")'
  # install Retriever python library
#  - sudo chmod -R 777 /usr/local/lib/python2.7/dist-packages .
  - pip install --user -U git+https://github.com/weecology/retriever.git@master
  - retriever update
#  - python -c "import retriever;retriever.check_for_updates();retriever.dataset_names()"
#  - python -c "import retriever;retriever.install_csv('portal')"
  - pip install --user psycopg2
  - pip install --user pymysql
#  - sudo ls -l
#  - sudo pip install pymysql
#  - sudo pip install psycopg2
#  - retriever install csv portal
#  - ls -l
#  - git clone https://github.com/weecology/retriever.git retriever
#  - cd retriever
#  - wget https://bootstrap.pypa.io/get-pip.py
#  - sudo $PYTHON get-pip.py
#  - rm -rf get-pip.py
#  - sudo $PYTHON -m pip install -r requirements.txt
#  - sudo pip install pytest-cov -U
#  - sudo pip install pytest-xdist -U
#  - sudo pip install  . -U
#  - cd ..
#  - rm -rf retriever/
#  - sudo rm -rf ~/.retriever
#  - sudo retriever update
#  - sudo retriever install csv portal
#  - sudo ls -l
#  - sudo pip install retriever
#  - sudo python -c "import retriever as rt;rt.check_for_updates();rt.dataset_names()"
  # Exports
  - export PYTHON_CONFIG=python${R_PYTHON_VERSION}-config
  - export PKG_LIBS=`$PYTHON_CONFIG --ldflags`
  - export PKG_CPPFLAGS=`$PYTHON_CONFIG --includes`
  - export PKG_CPPFLAGS+=" -D PYTHONLIBFILE=\\\"libpython${R_PYTHON_VERSION}.so\\\""
# database setup
before_script:
  - sudo sqlite3 --version
  - sudo psql -c 'create database testdb;' -U postgres
script:
  - R CMD build .
  - R CMD INSTALL *tar.gz
  - R CMD check *tar.gz --no-install --no-multiarch --no-examples
  - sudo python -c "import retriever"
#  - R -e 'library(reticulate); import("retriever")'
#  - R -e 'x = system("which retriever",intern=T);x = dirname(x); rdataretriever::use_RetrieverPath(x);rdataretriever::get_updates(); rdataretriever::install_csv('portal')'
#  - R -e 'system("whereis retriever")'
  - R -e 'library(testthat)'
  - R -e 'library(devtools);devtools::test()'
after_success:
  - sudo R -e 'library("covr");codecov()'